/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7cd9cb8e25b7064743413efe155f5cbe)
interface __BaseEnv_Env {
	STORAGE: R2Bucket;
	DB: D1Database;
	WRITE_LIMITER: RateLimit;
	LOGIN_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	USUARIO: "ladiega";
	PASSWORD: string;
	AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "USUARIO" | "PASSWORD" | "AUTH_SECRET">> {}
}
